admin_productos_empresa_index:
    path:  /addproducts/  
    defaults: { _controller: WsunBundle:Default:addProducts }
    requirements:
        _method:  GET|POST
        
entradas_list:
    path: /pruebas/entradas/
    defaults: { _controller: WsunBundle:Default:entradas}

wsun_lista_productos:
    path: /lista/productos/
    defaults: { _controller: WsunBundle:Default:listaProductos}

admin_productos_empresa_select:
    path:  /products/  
    defaults: { _controller: WsunBundle:Default:products }
wsun_consulta_categoria:
     path:  /subcategoria/ 
     defaults: { _controller: WsunBundle:Default:consultaSubcategoria }
    
productos_lista:
    path:  /productslista  
    defaults: { _controller: WsunBundle:Default:productsList }
    
    
addpedido_index:
    path:  /addpedido/{id}
    defaults: { _controller: WsunBundle:DetallePedido:addPedido,id: empresa }
    requirements:
        _method:  GET|POST

admin_reportes:
    path:  /reportes
    defaults: { _controller: WsunBundle:Admin:Reportes }

admin_generar_csv:
    path:  /cvs
    defaults: { _controller: WsunBundle:Admin:generateCsv }
    
admin_mas_vendido:
    path:  /masVendido
    defaults: { _controller: WsunBundle:Admin:masVendido }
    
wsun_admin_lista_pedidos:
    path:  /listaPedidos
    defaults: { _controller: WsunBundle:Admin:ListaPedidos }
    
wsun_admin_reportes_productos_empresa:
    path:  /reportes_empresa
    defaults: { _controller: WsunBundle:Admin:Empresa }
    
wsun_bundle_admin_reportes_empresaProd_ajax:
    path:  /consulta
    defaults: { _controller: WsunBundle:Admin:ConsultaAjax }
    
wsun_admin_departamento:
    resource: "@WsunBundle/Resources/config/routing/departamento.yml"
    prefix:   /admin/departamento

wsun_homepage:
    path:     /
    defaults: { _controller: WsunBundle:Default:index }
    methods:  GET
    
login:
    path: /login
    defaults: { _controller: "WsunBundle:Security:login" }
login_check:
    path: /login_check
logout:
    path: /logout
   
login2:
    path:     /entrar
    defaults: { _controller: WsunBundle:Security:login }    
wsun_contactos:
    path:  /contactos
    defaults: { _controller: WsunBundle:Default:contactos }

wsun_buscar:
    path:     /buscar
    defaults: { _controller: WsunBundle:Producto:buscar }

wsun_empresa:
    resource: "@WsunBundle/Resources/config/routing/empresa.yml"
    prefix:   /admin/empresa

wsun_admin_producto:
        resource: "@WsunBundle/Resources/config/routing/producto.yml"
        prefix:   /admin/producto

wsun_admin_categoria:
        resource: "@WsunBundle/Resources/config/routing/categoria.yml"
        prefix:   /admin/categoria

wsun_pedido:
        resource: "@WsunBundle/Resources/config/routing/pedido.yml"
        prefix:   /pedido

wsun_detallepedido:
        resource: "@WsunBundle/Resources/config/routing/detallepedido.yml"
        prefix:   /detallepedido
        
wsun_admin_user:
        resource: "@WsunBundle/Resources/config/routing/user.yml"
        prefix:   /admin/user
wsun_admin_role:
        resource: "@WsunBundle/Resources/config/routing/role.yml"
        prefix:   /admin/role
wsun_parametrodepartamento:
        resource: "@WsunBundle/Resources/config/routing/parametrodepartamento.yml"
        prefix:   /parametrodepartamento

WsunAnnotations:
    resource: "@WsunBundle/Controller/"
    prefix:   /
    type:     annotation         

wsun_reporte_consulta_departamento:
    path:  /departamento  
    defaults: { _controller: WsunBundle:Admin:consultaDepartamento }

wsun_reporte_consulta_pedido:
    path:  /productosConsulta  
    defaults: { _controller: WsunBundle:Admin:consultaProductos }

wsun_consulta_departamento:
    path:  /departamentoConsulta  
    defaults: { _controller: WsunBundle:Departamento:consultaDepartamento }