# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        WsunBundle\Entity\Usuarios:
            algorithm: sha512
            #bcrypt 
            #cost: 4
            encode-as-base64: true
            iterations: 10
        #FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        # ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: WsunBundle\Entity\Usuarios, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous:    ~
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check 
            logout:
                path: /logout
                target: /
                
       
          
    access_control:
        - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY] }
        #- { path: ^/admin, role: [ROLE_SUPER_ADMIN] }
        - { path: ^/wsun, roles: [ROLE_USER,ROLE_SUPER_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY] }