admin_producto_index:
    path:     /
    defaults: { _controller: "WsunBundle:Producto:index" }
    methods:  GET

admin_producto_show:
    path:     /{id}/show
    defaults: { _controller: "WsunBundle:Producto:show" }
    methods:  GET

admin_producto_new:
    path:     /new
    defaults: { _controller: "WsunBundle:Producto:new" }
    methods:  [GET, POST]

admin_producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "WsunBundle:Producto:edit" }
    methods:  [GET, POST]

admin_producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "WsunBundle:Producto:delete" }
    methods:  DELETE
wsun_subcategoria:
    path:  /subcategoria
    defaults: { _controller: WsunBundle:Producto:subcategoria }